server:
  port: 8081
  address: 0.0.0.0

auth:
  service:
    url: http://auth-service:8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:30090"   # frontend NodePort
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

      default-filters:
        - JwtAuthFilter

      routes:
        - id: iot-simulator-service
          uri: http://iot-simulator-service:8085
          predicates:
            - Path=/iot/**
          filters:
            - JwtAuthFilter
            - StripPrefix=0

        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        - id: health-data-service
          uri: http://health-data-service:8082
          predicates:
            - Path=/api/health-data/**
          filters:
            - JwtAuthFilter
            - StripPrefix=0

        - id: insurance-service
          uri: http://insurance-service:8083
          predicates:
            - Path=/insurance/**
          filters:
            - JwtAuthFilter
            - StripPrefix=0

        - id: analysis-service
          uri: http://analysis-service:8084
          predicates:
            - Path=/analysis/**
          filters:
            - JwtAuthFilter
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
