apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iot-simulator-pg-data
  namespace: ins
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-simulator-postgres
  namespace: ins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-simulator-postgres
  template:
    metadata:
      labels:
        app: iot-simulator-postgres
    spec:
      containers:
        - name: postgres
          imagePullPolicy: IfNotPresent
          image: postgres:15
          ports:
            - name: pg
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: iot_simulator_db
            - name: POSTGRES_USER
              value: iot_user
            - name: POSTGRES_PASSWORD
              value: iot_pass
          volumeMounts:
            - name: iot-simulator-pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: iot-simulator-pg-data
          persistentVolumeClaim:
            claimName: iot-simulator-pg-data
---
apiVersion: v1
kind: Service
metadata:
  name: iot-simulator-postgres
  namespace: ins
spec:
  selector:
    app: iot-simulator-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  type: ClusterIP