apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: health-pg-data
  namespace: ins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-postgres
  namespace: ins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-postgres
  template:
    metadata:
      labels:
        app: health-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - name: pg
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: healthdb
            - name: POSTGRES_USER
              value: health_user
            - name: POSTGRES_PASSWORD
              value: health_pass
          volumeMounts:
            - name: health-pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: health-pg-data
          persistentVolumeClaim:
            claimName: health-pg-data
---
apiVersion: v1
kind: Service
metadata:
  name: health-postgres
  namespace: ins
spec:
  selector:
    app: health-postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  type: ClusterIP