apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-service
  namespace: ins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance-service
  template:
    metadata:
      labels:
        app: insurance-service
    spec:
      containers:
        - name: insurance-service
          image: froleod/insurance-service:1.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8083
          env:
            - name: SPRING_APPLICATION_NAME
              value: "insurance-service"
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-service:8888"
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "true"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "20"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "1000"
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
  namespace: ins
spec:
  selector:
    app: insurance-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  type: ClusterIP